title: Menuju OSN Informatika
email: your-email@example.com
description: "Kumpulan sumber-sumber untuk persiapan menuju OSN Informatika, langsung dari Ikatan Alumni Tim Olimpiade Komputer Indonesia."

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# SEO
google_site_verification: 5NFkq82KvSC_u1zEZD0Dh6qFvxJ7MSi0XLZt5PxjhF4

# Build settings
markdown: kramdown
# theme: jekyll-theme-minimal
plugins:
  - jekyll-feed