# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

# Setup
gems: 				 [jekyll-paginate]
title:               'Olimpiade Komputer'
tagline:             'Kurikulum OSN 2017'
#description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://olimpiadekomputer.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              IA-TOKI
  url:               https:blog.ia-toki.org


# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Custom vars
version:             1.0.0
excerpt_separator: <!--more-->

collections:
  algoritma:
    output: true